#!/bin/sh

sig() {
    pid=`cat /tmp/molior.pid`
    echo "got sig $1, terminating molior (pid $pid)"
    kill $pid
    wait $supid
    exit 0
}
trap 'sig TERM' TERM

echo "Starting api (waiting for postgres 5s)"
sleep 5
echo MOLIOR_VERSION = \"`dpkg-parsechangelog -S Version`\" > molior/version.py

groupmod -g `stat -c %g /var/run/docker.sock` docker; \
chown molior /var/lib/molior/; \
/app/pkgdata/molior-server/usr/sbin/create-molior-keys "Molior Debsign" debsign@molior.info; \
mkdir -p /usr/lib/molior; \
cp /app/pkgdata/molior-common/usr/lib/molior/* /usr/lib/molior/; \
cp /app/pkgdata/molior-server/etc/sudoers.d/01_molior /etc/sudoers.d/; \
mkdir -p /etc/molior/mirror-hooks.d; \
ln -sf /usr/lib/molior/create-docker.sh /etc/molior/mirror-hooks.d/03-create-docker; \
mkdir -p /var/lib/molior/debootstrap/; \
mkdir -p /var/lib/molior/repositories/; \
chown molior /var/lib/molior/repositories/; \
mkdir -p /var/lib/molior/upload/; \
chown molior /var/lib/molior/upload/; \
mkdir -p /etc/molior; \
cp -ar docker/dev/backend-docker.yml docker/dev/molior.yml /etc/molior/; \
cp -ar /app/pkgdata/molior-server/usr/lib/* /usr/lib/; ./pkgdata/molior-server/usr/lib/molior/db-upgrade.sh ./pkgdata/molior-server/usr/share/molior/database && \

su molior -c 'adev runserver -q -p 9999 molior/ & pid=$!; echo -n $pid >/tmp/molior.pid; wait $pid' &
supid=$!
wait $supid
