#!/bin/sh

sig() {
    echo "got sig $1, terminating aptly (pid $pid)"
    kill -INT $pid
    exit 0
}
trap 'sig TERM' TERM

echo Starting aptly ...
usermod -u `stat -c %u /app` aptly
chown -R `stat -c %u /app` /var/lib/aptly
/usr/sbin/create-aptly-keys $REPOSIGN_NAME $REPOSIGN_EMAIL

su aptly -c "air -build.pre_cmd \"go mod tidy; go generate\" -build.exclude_dir system -build.exclude_dir debian -- api serve -listen 0.0.0.0:3142" &
pid=$!
wait $pid
