#!/bin/sh

sig() {
    echo "got sig $1, terminating ng serve (pid $pid)"
    kill -INT $pid
    exit 0
}
trap 'sig TERM' TERM

echo "export function MoliorWebVersion() { return \"`dpkg-parsechangelog -S Version`\"; }" > /app/src/app/lib/version.ts

echo Starting ng serve ...
PATH=node_modules/.bin:$PATH NODE_OPTIONS=--openssl-legacy-provider ng serve --poll=2000 --host 0.0.0.0 --base-href=/ --serve-path=/ --proxy-config /etc/ng-serve.proxy.conf.json --disable-host-check &
pid=$!
wait $pid
