#!/bin/sh

set -e

sig() {
    set +e
    echo "SIGTERM received, terminatig pid $suppid ..."
    kill $suppid
}
trap sig TERM INT
trap '' HUP

if [ -f /config/molior.yml ]; then
    cp /config/molior.yml /etc/molior/
    chown molior /etc/molior/molior.yml
fi

if [ -f /config/backend-docker.yml ]; then
    cp /config/backend-docker.yml /etc/molior/
    chown molior /etc/molior/backend-docker.yml
fi

if [ -f /config/backend-kubernetes.yml ]; then
    cp /config/backend-kubernetes.yml /etc/molior/
    chown molior /etc/molior/backend-kubernetes.yml
fi

if [ -n "$DEBSIGN_NAME" ] && [ -n "$DEBSIGN_EMAIL" ]; then
    echo "start: Creating gpgs key for '$DEBSIGN_NAME'"
    /usr/sbin/create-molior-keys $DEBSIGN_NAME $DEBSIGN_EMAIL
fi

if [ -e /var/run/docker.sock ]; then  # docker environment
    # allow accessing docker socker from host
    groupmod -g `stat -c %g /var/run/docker.sock` docker
fi

while true; do
    if su postgres -c "pg_isready -d molior" >/dev/null 2>&1; then
        break
    fi
    echo start: waiting for database connection ...
    sleep 1
done

/usr/lib/molior/db-upgrade.sh

su molior -c 'exec /usr/bin/python3 -m molior.main --host=0.0.0.0 --port=9999' &
suppid=$!
echo $suppid > /var/run/molior.pid
wait $suppid || true
wait || true
rm -f /var/run/molior.pid
touch /shutdown/molior-done
echo "start: molior terminated."
