#!/bin/sh

sig() {
    pid=`cat /tmp/postgres.pid`
    kill $pid
    wait $supid
    exit 0
}
trap 'sig TERM' TERM

pg_version=17

echo Starting postgres ...
su postgres -c "/usr/lib/postgresql/$pg_version/bin/postgres -D /var/lib/postgresql/$pg_version/main -c config_file=/etc/postgresql/$pg_version/main/postgresql.conf & pid=\$!; echo -n \$pid >/tmp/postgres.pid; wait \$pid" &
suppid=$!
wait $supid
