apiVersion: v1
kind: ConfigMap
metadata:
  name: molior-cm3
  labels:
    app: molior
data:
  aptly.conf: |
    {
      "rootDir": "/var/lib/aptly/.aptly",
      "downloadConcurrency": 4,
      "downloadSpeedLimit": 0,
      "downloadRetries": 0,
      "downloader": "default",
      "databaseOpenAttempts": -1,
      "architectures": [],
      "dependencyFollowSuggests": false,
      "dependencyFollowRecommends": false,
      "dependencyFollowAllVariants": false,
      "dependencyFollowSource": false,
      "dependencyVerboseResolve": false,
      "gpgDisableSign": false,
      "gpgDisableVerify": false,
      "gpgProvider": "gpg",
      "downloadSourcePackages": false,
      "skipLegacyPool": true,
      "ppaDistributorID": "ubuntu",
      "ppaCodename": "",
      "skipContentsPublishing": false,
      "skipBz2Publishing": false,
      "FileSystemPublishEndpoints": {},
      "S3PublishEndpoints": {},
      "SwiftPublishEndpoints": {},
      "AzurePublishEndpoints": {},
      "AsyncAPI": false,
      "enableMetricsEndpoint": false,
      "logLevel": "info",
      "logFormat": "default",
      "serveInAPIMode": false
    }

  backend-kubernetes.yml: |
    registry:
        server: "{{ .Values.registry.host }}:{{ .Values.registry.port }}"
        user: "{{ .Values.registry.user }}"
        password: "{{ .Values.registry.password }}"

    builder:
        amd64:
            parallel: {{ .Values.builder.amd64.parallel }}

  molior.yml: |
    # Molior configuration

    server:
        url: '{{ .Values.molior.serverUrl }}'

    hostname: '{{ .Values.molior.hostname }}'
    working_dir: '/var/lib/molior'
    database: '/molior'

    debsign_gpg_email: '{{ .Values.molior.debsignEmail }}'

    builds:
        version_prefix: "{{ .Values.molior.versionPrefix }}"

    ci_builds:
        enabled: {{ .Values.molior.ciBuildsEnabled }}
        packages_ttl: {{ .Values.molior.ciPackagesTtl }}

    admin:
        admin_password: '{{ .Values.molior.adminPassword }}'

    auth_backend: 'db'

    backend: '{{ .Values.molior.backend }}'

    max_parallel_chroots: {{ .Values.molior.maxParallelChroots }}

    aptly:
        apt_url_public: '{{ .Values.aptly.publicUrl }}'
        apt_url: '{{ .Values.aptly.internalUrl }}'
        api_url: '{{ .Values.aptly.apiUrl }}'
        api_user: '{{ .Values.aptly.user }}'
        api_pass: '{{ .Values.aptly.password }}'
        gpg_key: '{{ .Values.aptly.gpgKey }}'
        key: 'archive-keyring.asc'
