---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - image: {{ .Values.registry.host }}:{{ .Values.registry.port }}/molior-web:dev
          imagePullPolicy: Always
          name: molior-web
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/molior
              name: molior
      restartPolicy: Always
      volumes:
        - name: molior
          persistentVolumeClaim:
            claimName: molior
