apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: molior
    meta.helm.sh/release-namespace: molior
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
