---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  # namespace: molior
  name: molior-job-manager
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "delete"]
  - apiGroups: [""]
    resources: ["pods/log", "pods/status"]
    verbs: ["get"]
