apiVersion: v1
data:
  aptly.conf: |
    {
      "rootDir": "/var/lib/aptly/.aptly",
      "downloadConcurrency": 4,
      "downloadSpeedLimit": 0,
      "downloadRetries": 0,
      "downloader": "default",
      "databaseOpenAttempts": -1,
      "architectures": [],
      "dependencyFollowSuggests": false,
      "dependencyFollowRecommends": false,
      "dependencyFollowAllVariants": false,
      "dependencyFollowSource": false,
      "dependencyVerboseResolve": false,
      "gpgDisableSign": false,
      "gpgDisableVerify": false,
      "gpgProvider": "gpg",
      "downloadSourcePackages": false,
      "skipLegacyPool": true,
      "ppaDistributorID": "ubuntu",
      "ppaCodename": "",
      "skipContentsPublishing": false,
      "skipBz2Publishing": false,
      "FileSystemPublishEndpoints": {},
      "S3PublishEndpoints": {},
      "SwiftPublishEndpoints": {},
      "AzurePublishEndpoints": {},
      "AsyncAPI": false,
      "enableMetricsEndpoint": false,
      "logLevel": "info",
      "logFormat": "default",
      "serveInAPIMode": false
    }
  backend-kubernetes.yml: |
    registry:
        server-push: "molior-registry:5000"
        server: "localhost:5000"
        user: ""
        password: ""

    builder:
        amd64:
            parallel: 10
    #    arm64:
    #        remote_cmd: "ssh -o StrictHostKeyChecking=no builder@10.0.2.123"
    #        parallel: 2
  molior.yml: |
    # Molior configuration

    server:
        url: 'http://molior:9999'

    hostname: '127.0.0.1'
    working_dir: '/var/lib/molior'
    database: '/molior'

    # GPG email for signing the source packages
    debsign_gpg_email: 'debsign@molior'

    builds:
        # git tags to be built in stable need to start with the prefix:
        version_prefix: "v"

    ci_builds:
        enabled: True
        # Remove ci packages which are older than <ci_packages_ttl> days
        packages_ttl: 7

    admin:
        admin_password: 'molior-dev'

    auth_backend: 'db'

    backend: 'kubernetes'

    # Molior server settings
    max_parallel_chroots: 2

    # Aptly settings
    aptly:
        apt_url_public: 'http://localhost:8080'
        apt_url: 'http://aptly:8000'
        api_url: 'http://aptly:3143/api'
        api_user: 'molior'
        api_pass: 'molior-dev'
        gpg_key: 'reposign@molior'
        key: 'archive-keyring.asc'
kind: ConfigMap
metadata:
  labels:
    molior.service: molior
  name: molior-cm3
