apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    molior.service: registry
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      molior.service: registry
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        molior.service: registry
    spec:
      containers:
        - image: molior_registry
          imagePullPolicy: Never
          name: molior-registry
          env:
            - name: REGISTRY_USER
              valueFrom:
                configMapKeyRef:
                  key: REGISTRY_USER
                  name: env
            - name: REGISTRY_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: REGISTRY_PASSWORD
                  name: env
          ports:
            - containerPort: 5000
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/docker-registry/
              name: registry
      restartPolicy: Always
      volumes:
        - name: registry
          persistentVolumeClaim:
            claimName: registry

