apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    molior.service: aptly
  name: aptly
spec:
  replicas: 1
  selector:
    matchLabels:
      molior.service: aptly
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        molior.service: aptly
    spec:
      containers:
        - name: aptly-server
          image: aptly:dev
          imagePullPolicy: Never
          env:
            - name: REPOSIGN_EMAIL
              valueFrom:
                configMapKeyRef:
                  key: REPOSIGN_EMAIL
                  name: env
            - name: REPOSIGN_NAME
              valueFrom:
                configMapKeyRef:
                  key: REPOSIGN_NAME
                  name: env
          ports:
            - containerPort: 3143
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/aptly
              name: aptly

        - name: aptly-nginx
          image: molior-nginx:dev
          imagePullPolicy: Never
          env:
            - name: APTLY_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: APTLY_PASSWORD
                  name: env
            - name: APTLY_USER
              valueFrom:
                configMapKeyRef:
                  key: APTLY_USER
                  name: env
            - name: APTLY_URL
              value: http://localhost:3142
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/aptly
              name: aptly
      restartPolicy: Always
      volumes:
        - name: aptly
          persistentVolumeClaim:
            claimName: aptly
