---
apiVersion: v1
kind: Service
metadata:
  labels:
    molior.service: molior
  name: molior
spec:
  ports:
    - name: "9999"
      port: 9999
      targetPort: 9999
  selector:
    molior.service: molior
