apiVersion: v1
kind: Service
metadata:
  labels:
    molior.service: repo
  name: repo
spec:
  type: NodePort
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
      nodePort: 30088
  selector:
    molior.service: aptly
