#!/bin/sh

set -e

sig() {
    pid=`cat /tmp/aptly.pid`
    echo "got sig $1, terminating aptly (pid $pid)"
    kill $pid
    wait $supid
    exit 0
}
trap 'sig TERM' TERM

echo Starting aptly ...

# Set aptly user id from volume
vuid=`stat -c %u /var/lib/aptly`
if [ $vuid -eq 0 ]; then
    chown -R aptly /var/lib/aptly
else
    usermod -u `stat -c %u /var/lib/aptly` aptly >/dev/null
fi

if [ -n "$REPOSIGN_NAME" ] && [ -n "$REPOSIGN_EMAIL" ]; then
    echo "Creating gpgs key for '$REPOSIGN_NAME'"
    create-aptly-keys $REPOSIGN_NAME $REPOSIGN_EMAIL
fi

# Copy aptly configuration
if [ -f "/config/aptly.conf" ]; then
    cp -f /config/aptly.conf /var/lib/aptly/.aptly.conf
    chown aptly /var/lib/aptly/.aptly.conf
fi

su aptly -c 'aptly api serve -listen 0.0.0.0:3142 & pid=$!; echo -n $pid >/tmp/aptly.pid; wait $pid' &
suppid=$!
wait $supid
